name: End-to-end tests
  on:
    pull_request:
    push:
      branches-ignore:
        - main
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm run dev
